/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import services.CrudApi;

/**
 *
 * @author vicmn
 */
public class Residentes extends javax.swing.JFrame {
    public static Residentes instancia = null;
    private String token = "";
    private CrudApi servicios = new CrudApi();
    /**
     * Creates new form Residentes
     */
    public Residentes() {
        initComponents();
        this.setBounds(0, 0, 950, 600);
        

    }
    
    public void loadTable() {
        //Definimos el token para acceder a la API
        servicios.setToken(token);
        //Lista
         String[] columnNames = {"N°", "CI", "Nombre", "Nacimiento", "Ingreso", "Familiar referente", "Teléfono Familiar"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        table.setBounds(panelLista.getBounds());
        table.setFont(new Font("SansSerif", Font.PLAIN, 14));
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setFillsViewportHeight(true); // Para que la tabla sea scrollable
        try {
                String response = servicios.listResidents();
                JSONArray jsonArray = new JSONArray(response);

                // Limpiar datos anteriores
                model.setRowCount(0);

                // Procesar JSON y añadir a la tabla
                for (int i = 0; i < jsonArray.length(); i++) {
                    JSONObject jsonObject = jsonArray.getJSONObject(i);
                    Object[] row = {
                            jsonObject.getInt("id"),
                            jsonObject.getInt("ci"),
                            jsonObject.getString("name"),
                            jsonObject.getString("birth_date"),
                            jsonObject.getString("entry_date"),
                            jsonObject.getString("family_name"),
                            jsonObject.getString("family_phone"),

                    };
                    model.addRow(row);
                }
                table.setModel(model);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al consultar residentes: " + ex.getMessage());
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelNuevo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de residentes");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(java.awt.SystemColor.activeCaption);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 600));

        panelLista.setBackground(java.awt.SystemColor.controlHighlight);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton1.setText("Actualizar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Eliminar residente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista", panelLista);

        javax.swing.GroupLayout panelNuevoLayout = new javax.swing.GroupLayout(panelNuevo);
        panelNuevo.setLayout(panelNuevoLayout);
        panelNuevoLayout.setHorizontalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        panelNuevoLayout.setVerticalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("+ Agregar nuevo", panelNuevo);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 500));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Lista");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int fila = table.getSelectedRow();
        int idResidente = (int) table.getValueAt(fila, 0);
        String nombreResidente = table.getValueAt(fila,2).toString();
        int decision = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea eliminar el residente N° " + idResidente + " - Nombre: "+nombreResidente+"? \n ESTA ACCIÓN ES IRREVERSIBLE", "PRECAUCIÓN", JOptionPane.YES_NO_CANCEL_OPTION);
        switch(decision){
                case 0: 
            {
                try {
                    servicios.deleteResident(idResidente);
                    JOptionPane.showMessageDialog(null, "Residente eliminado");
                    loadTable();

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Hubo un error al eliminar el residente");
                    Logger.getLogger(Residentes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                    break;

                case 1: 
                    JOptionPane.showMessageDialog(null, "No se eliminará al residente");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Operación cancelada");
                    break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int fila = table.getSelectedRow();
         if(fila < 0) {
                      JOptionPane.showMessageDialog(null, "No se está seleccionando ningún registro a modificar");
         } else {
                String idResidente = table.getValueAt(fila, 0).toString();
                String ciResidente = table.getValueAt(fila, 1).toString();
                String nombreResidente = table.getValueAt(fila,2).toString();
                String fechaNacimiento = table.getValueAt(fila, 3).toString();
                String fechaIngreso = table.getValueAt(fila, 4).toString();
                String nombreFamiliar = table.getValueAt(fila, 5).toString();
                String telefonoFamiliar = table.getValueAt(fila, 6).toString();
                int decision = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea MODIFICAR el residente N° " + idResidente + " - Nombre: "+nombreResidente+"? \n ESTA ACCIÓN ES IRREVERSIBLE \n"
                        + "Nuevos datos: \n"
                        + "ID: "+idResidente+"\n"
                        + "Nombre: "+nombreResidente+"\n"
                        + "CI: "+ciResidente+"\n"
                        + "Fecha de nacimiento: " +fechaNacimiento+"\n"
                        + "Fecha de ingreso: "+fechaIngreso+"\n"
                        + "Familiar de referencia: "+nombreFamiliar+"\n"
                        + "Teléfono de referencia: "+telefonoFamiliar+"\n"
                        , "PRECAUCIÓN", JOptionPane.YES_NO_CANCEL_OPTION);
                switch(decision){
                        case 0: 
                    {
                        try {
                            servicios.updateResident(idResidente, nombreResidente, ciResidente, fechaNacimiento, fechaIngreso, nombreFamiliar, telefonoFamiliar);
                            JOptionPane.showMessageDialog(null, "Residente modificado");
                            loadTable();

                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(null, "Hubo un error al modificar el residente");
                            Logger.getLogger(Residentes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                            break;

                        case 1: 
                            JOptionPane.showMessageDialog(null, "No se modificará al residente");
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Operación cancelada");
                            break;
                }
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Residentes().setVisible(true);
            }
        });
    }
    
    public static Residentes getInstancia(String token) {
        if (instancia == null) {
            instancia = new Residentes();
            instancia.setToken(token);
            return instancia;
        }
        return instancia;
    }
    
    public void setToken(String t) {
        token = t;
        loadTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelNuevo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
